-- Project: E-Commerce Sales Analysis
-- Database Used: Oracle (Oracle APEX)
-- Description: Data cleaning, transformation, KPI calculation and sales analysis

SELECT * FROM AMAZON_SALES_DATA

DESC AMAZON_SALES_DATA

SELECT * 
FROM AMAZON_SALES_DATA
FETCH FIRST 10 ROWS ONLY;

SELECT ORDER_ID, COUNT(*)
FROM AMAZON_SALES_DATA
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;

SELECT DISTINCT DATE_
FROM AMAZON_SALES_DATA
FETCH FIRST 5 ROWS ONLY

CREATE TABLE AMAZON_SALES_DATASET AS
SELECT 
    ID,
    ORDER_ID,
    TO_DATE(DATE_, 'DD-MM-YYYY') AS ORDER_DATE,
    PRODUCT,
    CATEGORY,
    PRICE,
    QUANTITY,
    TOTAL_SALES,
    CUSTOMER_NAME,
    CUSTOMER_LOCATION,
    PAYMENT_METHOD,
    STATUS,
    TOTAL_SALES * 0.2 AS PROFIT,
    TOTAL_SALES * 0.8 AS COST
FROM AMAZON_SALES_DATA;

DESC AMAZON_SALES_DATASET;

SELECT EXTRACT(MONTH FROM ORDER_DATE) AS MONTH,
       SUM(TOTAL_SALES) AS MONTHLY_SALES
FROM AMAZON_SALES_DATASET
GROUP BY EXTRACT(MONTH FROM ORDER_DATE)
ORDER BY MONTH;

SELECT 
    TO_CHAR(ORDER_DATE, 'MON') AS MONTH,
    SUM(TOTAL_SALES) AS MONTHLY_SALES
FROM AMAZON_SALES_DATASET
GROUP BY TO_CHAR(ORDER_DATE, 'MON')
ORDER BY MIN(ORDER_DATE);

-----TOTAL REVENUE----------
SELECT SUM(TOTAL_SALES) AS TOTAL_REVENUE
FROM AMAZON_SALES_DATASET;

------TOTAL PROFIT----------
SELECT SUM(PROFIT) AS TOTAL_PROFIT
FROM AMAZON_SALES_DATASET;

-------TOTAL ORDERS---------
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM AMAZON_SALES_DATASET;

-------TOTAL QUANTITY SOLD-------
SELECT SUM(QUANTITY) AS TOTAL_QUANTITY
FROM AMAZON_SALES_DATASET;

--------PROFIT MARGIN %---------
SELECT 
ROUND((SUM(PROFIT) / SUM(TOTAL_SALES)) * 100, 2) AS PROFIT_MARGIN_PERCENT
FROM AMAZON_SALES_DATASET;

------CATEGORY ANALYSIS---------
SELECT 
    CATEGORY,
    SUM(TOTAL_SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT,
    ROUND((SUM(PROFIT)/SUM(TOTAL_SALES))*100,2) AS PROFIT_MARGIN
FROM AMAZON_SALES_DATASET
GROUP BY CATEGORY
ORDER BY TOTAL_SALES DESC;

------LOCATION ANALYSIS-----------
SELECT 
    CUSTOMER_LOCATION,
    SUM(TOTAL_SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM AMAZON_SALES_DATASET
GROUP BY CUSTOMER_LOCATION
ORDER BY TOTAL_SALES DESC;

------TOP 5 PRODUCTS------------
SELECT *
FROM (
    SELECT 
        PRODUCT,
        SUM(TOTAL_SALES) AS TOTAL_SALES
    FROM AMAZON_SALES_DATASET
    GROUP BY PRODUCT
    ORDER BY TOTAL_SALES DESC
)
WHERE ROWNUM <= 5;

--------ORDER STATUS ANALYSIS-------
SELECT 
    STATUS,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(TOTAL_SALES) AS TOTAL_SALES
FROM AMAZON_SALES_DATASET
GROUP BY STATUS;